name: aqoon_bile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  intl_phone_number_input: ^0.7.1
  lottie: ^2.0.0
  introduction_screen: ^3.1.0
  jiffy: ^5.0.0
  flutter_staggered_animations: ^1.1.1
  animated_widgets: ^1.1.0
  shimmer: ^2.0.0
  badges: ^2.0.3
  pull_to_refresh: ^2.0.0
  google_fonts: ^3.0.1
  dotted_decoration: ^2.0.0
  money_formatter: ^0.0.3
  extended_image: ^6.3.2
  like_button: ^2.0.5
  get_storage: ^2.0.3
  http: ^0.13.5
  modal_progress_hud_nsn: ^0.3.0
  iconly: ^1.0.1
  water_drop_nav_bar: ^2.2.0+4
  flappy_search_bar_ns: ^2.0.2
  webview_flutter: ^4.0.1
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.2
  connectivity_wrapper: ^1.1.1
  fluttertoast: ^8.1.2
  after_layout: ^1.2.0
  auto_size_text: ^3.0.0
  pod_player: ^0.0.6
  flutter_svg: ^1.1.6
  url_launcher: ^6.1.7
  line_icons: ^2.0.1
  #flutter_widget_from_html: ^0.9.1
  vimeo_video_player: ^0.0.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  flutter_test: 
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.jpg"
 
flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/locales/
    - assets/icons/

  fonts: 
    - family: BaiJamjuree
      fonts: 
        - asset: assets/fonts/BaiJamjuree-Medium.ttf

